### ISSUE TITLE
Migrate GSoC Content

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-community#1]
Per discussion on slack the GSoC related content* should be migrated to this repo.

*Ex:

- www.owasp.org/index.php/GSoC*_Ideas
- https://www.google.com/search?q=gsoc+site%3Aowasp.org&oq=gsoc+site%3Aowasp.org

My current plan is to create a `gsoc` folder within `https://github.com/OWASP/www-community/tree/master/pages`

<sub>Feel free to assign this issue to me.</sub>

**Comment by hblankenship** [comment]
Thanks for volunteering to migrate this!

**Comment by kingthorin** [comment]
Should I be creating markdown or html files? How are they supposed to be cross linked? Do I need to establish permalinks for every file?

The existing "Recently Submitted Files" on the index.md doesn't seem to be working. The associated md files have permalinks which 404. (Nor do they seem to be available via any combination of filename/.html/.md. (The permalinks do work within the www-community path, ex: https://www2.owasp.org/www-community/xss)

**Comment by kingthorin** [comment]
As a concrete example, let's assume the following structure:
```console
└───pages
    │   ..existing md files (xss etc)
    │
    └───gsoc
            gsoc2019.md
            gsoc_sat.md
            index.md
```
I assume when visiting www2.owasp.org/www-community/gsoc that index.md will be displayed. So how should it link to gsoc2019.md?

How should gsoc2019.md link to gsoc_sat.md? What literal tags should I be using?
`[GSoC SAT](gsoc_sat.md)`
`[GSoC SAT](./gsoc_sat.md)`
`[GSoC SAT](gsoc_sat)`
other?

**Comment by hblankenship** [comment]
You do not necessarily need permalinks.  I just did it for things that seem to make sense.  You _could_ permalink the items.  I fixed the current crop of links in the recently submitted files (we'll see if that works for new ones).

According to your example, you may use the index.md or not.  I suggest that it becomes a GSoC overview page and contains links within it to the gsoc2019, gsoc_sat files.  

The correct links would be your last example:
[GSoC SAT](gsoc_sat)

**Comment by kingthorin** [comment]
Thanks! :+1:

**Comment by hblankenship** [comment]
I have added an info.md file to the community site and put 'Attacks' and 'Vulnerabilities' there.  Would be interested in putting Initiatives there and possibly removing the tab?

**Comment by kingthorin** [comment]
Sure the tab content could be moved to index.md inside the initiatives directory and linked that way from info.md. If you're good with that let me know and I'll include that change when I do the last two GSoC pages.

**Comment by hblankenship** [comment]
sounds good.  I already added the info to an index.md file under initiatives when I did the attacks/vulns thing so that file would just need to be updated.  I also added info.md files into attacks and vulnerabilities folders if you want to duplicate that in gsoc (basically for navigating back to community).

**Comment by kingthorin** [comment]
Sounds good, thanks!

**Comment by kingthorin** [comment]
FYI I do plan to have the last two years of GSoC content knocked off before the 20th.
