### ISSUE TITLE
ZAP is now Checkmarx

### ISSUE THREAD

**Issue by sydseter** [OWASP/www-community#1001]
**Describe what change you would like** :  
ZAP is now owned by Checkmarx and is in their portfolio, and we should not be seen to endorse one company's products and not another company's products. It is probably easier to remove the section on ZAP

In addition some ZAP features will now become paid-for, which is not truly open source

**Context** :  
[Section: 08-verification/02-tools/01-zap.md](https://owasp.org/www-community/Free_for_Open_Source_Application_Security_Tools)

see: https://github.com/OWASP/www-project-developer-guide/issues/282

**Comment by psiinon** [comment]
ZAP is NOT owned by Checkmarx :)
I've explained that in https://www.zaproxy.org/blog/2024-09-24-zap-has-joined-forces-with-checkmarx/
The 3 ZAP project leaders _are_ employed by Checkmarx.
But the rights to ZAP remain with the ZAP Core Team and ZAP is staying OSS.

**Comment by thc202** [comment]
> In addition some ZAP features will now become paid-for, which is not truly open source

Which ones?

**Comment by sydseter** [comment]
see discussion on this here: https://github.com/OWASP/www-project-developer-guide/issues/282

It was too rushed from my side.
