### ISSUE TITLE
Incorrect Format_string_attack example

### ISSUE THREAD

**Issue by meir555** [OWASP/www-community#108]
In the page:

https://github.com/OWASP/www-community/blob/master/pages/attacks/Format_string_attack.md

There is an example of a format string attack.
The example is:

> int main (int argc, char **argv) {    
> char buf [100];    int x = 1 ;     
> snprintf ( buf, sizeof buf, argv [1] ) ;    
> buf [ sizeof buf -1 ] = 0;    
> printf ( “Buffer size is: (%d) \nData input: %s \n” , strlen (buf) , buf ) ;    
> printf ( “X equals: %d/ in hex: %#x\nMemory address for x: (%p) \n” , x, x, &x) ;    
> return 0 ; }

And the explanation is that the %x or %s gets expanded in the `printf` function.
This is completely wrong.
The crash happens in the line of `snprintf `, NOT in the `printf` line.

The line `printf ( “Buffer size is: (%d) \nData input: %s \n” , strlen (buf) , buf ) ;` is safe!
And `printf("my string is %s", "%s%s%s%s%s%s%s")` will NOT cause a crash

**Comment by kingthorin** [comment]
Thanks @meir555 are you able to submit a PR with a fix?

**Comment by meir555** [comment]
The whole section of example 1 should be written from the beginning, with a very simple example:

```
#include  <stdio.h> 
void main(int argc, char **argv)
{
	// This line is not vulnerable
	printf("%s", argv[1]);

	// This line is vulnerable
	printf(argv[1]);
}

```

**Comment by kingthorin** [comment]
So that’s a yes? :wink:

**Comment by meir555** [comment]
OK

**Comment by meir555** [comment]
Done. See pool 109.
Please check the grammar and spelling.
