### ISSUE TITLE
Asset storage needs a plan

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-community#11]
```console
Receiving objects: 100% (3022/3022), 4.36 GiB | 25.37 MiB/s, done.
```

That's going to prevent community contribution in some cases. Even on half-gig service that just took me a few minutes. People with lesser service just won't bother in the future.

**Comment by hblankenship** [comment]
You have a point about that.  This was on our 'needs to be mapped ASAP' list.  I will bring it up as an item for moving elsewhere in the site.

**Comment by kingthorin** [comment]
I don't think there's a rush, it could be tackled late in Jan and probably not cause too much upset between now and then. Glad it's on the radar 😀

**Comment by hblankenship** [comment]
as issue 12, these were moved outside this repo

**Comment by kingthorin** [comment]
Ref: https://github.com/OWASP/www-community/pull/221
