### ISSUE TITLE
FAQ SQL injection training link dead

### ISSUE THREAD

**Issue by harrisonSoS** [OWASP/www-community#120]
Regarding www-community/pages/OWASP_Application_Security_FAQ.md 
Under the [Where can I try out my testing skills....](https://github.com/OWASP/www-community/blob/master/pages/OWASP_Application_Security_FAQ.md#where-can-i-try-out-my-testing-skills-is-there-a-sample-application-i-can-practice-with) heading is this link: http://www.hackingzone.org/sql/index.php which redirects to a dead page.

**Comment by ADubhlaoich** [comment]
I'll hit this page tomorrow and add in some of the contemporary options, as well as clean up the formatting.

**Comment by kingthorin** [comment]
Tks!
