### ISSUE TITLE
OWASP SonarQube Project - broken link

### ISSUE THREAD

**Issue by KarlisVe** [OWASP/www-community#129]
Link [OWASP SonarQube Project](https://owasp.org/www-community/OWASP_SonarQube_Project) is broken.
It has even [docker image](https://github.com/OWASP/sonarqube), but due to broken links - it is very unclear how maintained this project is.

**Comment by kingthorin** [comment]
@hblankenship this seems to be an issue for the owasp .github.io repo could you move it please?

**Comment by kingthorin** [comment]
Perhaps I'm wrong, could be links within https://owasp.org/www-community/Source_Code_Analysis_Tools that are broken.

Though I can't seem to find any such project on the new site either.

**Comment by hblankenship** [comment]
Most, if not all, of those projects on the SCAT page are no longer active.  That said, I updated the links to either point to their current project page or to their github page if they are no longer listed as an OWASP project.

**Comment by kingthorin** [comment]
Thanks!
