### ISSUE TITLE
Aditional informations

### ISSUE THREAD

**Issue by Mirashx86** [OWASP/www-community#16]
This will be nice if you add here -> https://github.com/OWASP/www-community/blob/master/pages/attacks/Format_string_attack.md

```
int a=1,b=2,c=3;
printf("c: %3$d b: %2$d a: %1$d",a,b,c) - this describe how to manipulate parameters co compres payload
printf("%1$1000000d %2$n \n",a,b); - this show how to expand format output for memory overflow
```

<sub>Edited a few minor typos</sub>

**Comment by kingthorin** [comment]
Go for it, we look forward to your pull request ☺

**Comment by kingthorin** [comment]
@Mirashx86 The article has been largely re-written, could you take a look and let us know if this is still needed somewhere?

**Comment by kingthorin** [comment]
No feedback in months, assuming issue addressed by existing changes. Closing.
