### ISSUE TITLE
Migrate OWASP BugBounty Page

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-community#18]
https://wiki.owasp.org/index.php/Get_Started_with_OWASP_Bug_Bounty

@mikemccamon or @hblankenship any thoughts on where this should be located/linked, etc?

**Comment by hblankenship** [comment]
Wow.  That page hasn't been updated since 2016 and, other than ZAP, I have no idea if the others are still using it (and it looks like some of those projects are no longer active).

Do you think these should live on the individual project pages?  Perhaps a side bar item?  Bug Bounty

**Comment by kingthorin** [comment]
Is there someone within the org in charge of the BB program these days? This came up because there was a new ZAP release yesterday and I went to update BB program details ⚡️ 

I guess if ZAP is the only project really still engaged then it could be orphaned/abandon?

**Comment by hblankenship** [comment]
ZAP is the only project I know that uses it; I will email the project leads that are on the old page and ask who else might be using it still.

**Comment by kingthorin** [comment]
Thanks

**Comment by kingthorin** [comment]
Any news?

**Comment by hblankenship** [comment]
Yes.  I intend to migrate this over when I get a chance.  CSRFGuard, Zap, and HTML Sanitizer all indicate they use it.
