### ISSUE TITLE
XSS Filter Evasion Cheat Sheet: Hide malicious attributes to whitelist approach filters using a single slash

### ISSUE THREAD

**Issue by RobinMeis** [OWASP/www-community#189]
I've found a way to bypass certain filters which implement the following behaviour: The filter checks everything between opening and closing or opening and opening brackets. A whitelist is checked against the HTML tag as well as every attribute found within the brackets. Whenever an attribute is not whitelisted the filter will block the input. Closing tags are detected as soon as a slash is found between both brackets. As they aren't considered to contain malicious attributes they are always permitted.

Most HTML tags  are opened and closed like this:
`<p style="color:blue;">Text</p>`
Normally closing tags don't contain any attributes. I found that some filters skip checking for further attributes as soon as they see a slash as they expect to handle a closing tag. Thus it is possible to inject the following JavaScript:
`<img src="fail.jpg" / onerror="alert('XSS')">` while `<img src="fail.jpg" onerror="alert('XSS')">` gets blocked. The execution of the injected JavaScript has been verified in Firefox 68.9.0 ESR and Chromium 80.0.3987.162. A demonstration can be found in the following video: https://www.youtube.com/watch?v=KBOYJQ45k00

I think this is something which should be considered to be added to the XSS Filter Evasion Cheat Sheet.

**Comment by kingthorin** [comment]
Sounds reasonable, go for it.

**Comment by jmanico** [comment]
Can you kindly resubmit this bug against the cheatsheet itself vs the community page?

Nice work, thank you.

--
Jim Manico
@Manicode

**Comment by kingthorin** [comment]
I believe they were referring to the local community resource: https://github.com/OWASP/www-community/blob/c3f0657caf343e39e0bd886c34a006fc10ce0567/pages/xss-filter-evasion-cheatsheet.md

**Comment by jmanico** [comment]
All,

This filter evasion cheatsheet was removed from the cheatsheet series against my wishes, in a haphazard way. The community page still refers to itself as a cheatsheet, and it’s place in the cheatsheet project, but was removed from the project without cleaning up the page to refer to it as a standalone page.

This is all a shame because this is the first cheatsheet in the series history, and I made promises about this cheatsheet to Robert Hansen, who is the original author, promises that I feel are now broken.

So yea, wherever you folks want to do, but my request is that you integrate this page back into the cheat sheet series where it belongs.

Regards,
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by kingthorin** [comment]
@RobinMeis I'd suggest just modifying the local doc for now. If the CS project decides to pickup the content and maintain it going forward it can always be moved/removed in another PR.

**Comment by kingthorin** [comment]
@RobinMeis are you going to be able to tackle this?

**Comment by kingthorin** [comment]
@RobinMeis are you going to be able to tackle this?

**Comment by kingthorin** [comment]
@jmanico is the Cheat Sheet series picking this up?

**Comment by jmanico** [comment]
Let me talk to my co-lead first but if we do it  we’ll edit this page and point to the new cheatsheet location.

I am one of the only people asking to do this, so if anyone prefers the current location let me know and we can work it out.

--
Jim Manico
@Manicode

**Comment by kingthorin** [comment]
@jmanico any update?

**Comment by kingthorin** [comment]
@jmanico is the Cheat Sheet series picking this up?

**Comment by decidedlygray** [comment]
It looks like the XSS Filter Evasion Cheatsheet now has 2 homes:

https://github.com/OWASP/www-community/blob/master/pages/xss-filter-evasion-cheatsheet.md
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XSSFilterEvasionCheatSheet.md

Judging by the blame history the CheatSheetSeries version is just a fork of the community page created 24 days ago

**Comment by kingthorin** [comment]
Thanks @decidedlygray I’ll put a placeholder or redirect in place and close this issue in the next few days.

**Comment by dpuga1** [comment]
What the fuck is this aboit

**Comment by jmanico** [comment]
We are just moving the cheatsheet back into the series. I’ll have the community version point to the cheatsheet version soon.

This CS was originally donated by Robert Hansen (RSnake) to the cheatsheet series directly and I was the original wiki editor who brought it in with his permission, it’s just coming home.

--
Jim Manico
@Manicode

**Comment by kingthorin** [comment]
Redirect done.
