### ISSUE TITLE
All initiative pages 404 after changes 5d ago

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-community#19]
I had tested them all 12d ago after our last round of changes. Since then there was another set of changes 5days ago and they all 404 now https://github.com/OWASP/www-community/commits/master/pages/initiatives

**Comment by hblankenship** [comment]
Not sure why adding the slash at the end of index.md would cause such a big issue here.  Fixed.

**Comment by kingthorin** [comment]
Thank you, confirmed fixed.

**Comment by kingthorin** [comment]
This is broken again

**Comment by kingthorin** [comment]
From https://owasp.org/www-community/initiatives/ the links on the page are:
https://owasp.org/www-community/initiatives/initiatives/code_sprint
https://owasp.org/www-community/initiatives/initiatives/gsoc

duplicating "initiatives".

**Comment by hblankenship** [comment]
Hrmm.  Nothing changed with index....what in the world?

**Comment by hblankenship** [comment]
fixed by removing what was added to fix it before; methinks there is something rotten in Denmark.

**Comment by kingthorin** [comment]
Hahaha oh no
