### ISSUE TITLE
Hyperlink for Owasp Top Ten Project

### ISSUE THREAD

**Issue by rushendraChowdary** [OWASP/www-community#205]
Hyperlink for OWASP Top Ten Project is redirecting to 404 page, i guess the url is broken

**Comment by kingthorin** [comment]
There are a couple hundred pages in the www-community repo. Mind telling us what URL you were on when you encountered the issue?

**Comment by rushendraChowdary** [comment]
one the https://owasp.org/www-community/vulnerabilities/ url when i try clicking on OWASp Top Ten Project hyperlink.

**Comment by kingthorin** [comment]
Thanks
