### ISSUE TITLE
Write-what-where - no such article

### ISSUE THREAD

**Issue by heinosasshallik** [OWASP/www-community#224]
In this article:

https://github.com/OWASP/www-community/blob/master/pages/vulnerabilities/Using_freed_memory.md

There is a hyperlink to [write-what-where condition](https://owasp.org/www-community/vulnerabilities/Write-what-where_condition).

Such an article does not exist.

**Comment by kingthorin** [comment]
I accidentally pushed the fix directly. If anyone has comments/concerns add them here.
