### ISSUE TITLE
Adopt gender-neutral standards detailed in the Mobile Testing Security Guide

### ISSUE THREAD

**Issue by robhanlon22** [OWASP/www-community#229]
Hi there, I was taking a look at some of these documents and I noticed that many of them use gendered pronouns, most of which are he/him/his. The OWASP Mobile Security Testing Guide has guidelines for pronoun use: https://github.com/OWASP/owasp-mstg/pull/1586 I think that these should be adopted here, and existing pronoun uses audited.

**Comment by kingthorin** [comment]
Yup that makes sense. Feel free to start opening Pull Requests with adjustments.

The majority of the content in www-community was contributed globally via the org’s previous media wiki site since the early 2000s.

**Comment by kingthorin** [comment]
This may also be a good case to start implementing textlint.

Similar to: https://github.com/OWASP/wstg/issues/494

**Comment by kingthorin** [comment]
@robhanlon22 please have a look at: https://github.com/OWASP/www-community/pull/230 and let me know if you see anything amiss.
