### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Foster024** [OWASP/www-community#233]
##Hey. I apologize for my poor English.
I'm trying to intercept the traffic of the system process "SYSTEM (pid 4)", but I can not do this on my computer. Therefore, I use the MITM attack method, redirect the traffic of interest to owasp through my router using the iptables rule:
`iptables -t nat -A PREROUTING --dst 10 * .19. ***. 119 -p tcp --dport 443 -j DNAT --to-destination 192.168.1.93`
where local 192.168.1.93 is the IP and OWASP zap port, `10*.19.***.119` is the recipient address of the HTTPS packets that I need modify the packets in WASP and forward to `10*.19.***.**120**: 443`
`10*.19.***.120:443,  10*.19.***.119:443`- is HTTPS ssl server port
![11](https://user-images.githubusercontent.com/47894373/87555291-b296a080-c6ce-11ea-9c8e-caea71175726.png)
![12](https://user-images.githubusercontent.com/47894373/87555318-b9bdae80-c6ce-11ea-9779-496bf2a61893.png)
But I get an error in the browser.
PS: owasp certificate was imported into the system.
![13](https://user-images.githubusercontent.com/47894373/87555899-76177480-c6cf-11ea-9cf7-3e575836cec8.png)

RUS description of trouble
Привет. Прошу прощения за мой плохой английский.
Я пытаюсь перехватить трафик системного процесса "SYSTEM (пид 4)", но не могу этого сделать на своём компьютере. Поэтому я использую метод атаки MITM, перенаправляю в owasp интересующий меня траффик через мой роутер используя iptables правило:
`iptables -t nat -A PREROUTING --dst 10*.19.***.119 -p tcp --dport 443 -j DNAT --to-destination 192.168.1.93:443`
где локальный 192.168.1.93:443 - IP и порт OWASP zap, `10*.19.***.119 `- адрес получателя ХТТПС пакетов, которые мне нужно перехватить и отправить на `10*.19.***.120:443`
`10*.19.***.120:443,  10*.19.***.119:443` - это HTTPS ssl server port
Но я получаю ошибку в браузере.
ПС: сертификат owasp был импортирован в ситеме.

**Comment by kingthorin** [comment]
This community web repo doesn't support ZAP. If you wish to get community support for Zaproxy you should checkout the [ZAP User Group](https://groups.google.com/g/zaproxy-users).
