### ISSUE TITLE
404 for reference link to different types of XSS

### ISSUE THREAD

**Issue by jerrinss5** [OWASP/www-community#26]
The page https://owasp.org/www-community/Types_of_Cross-Site_Scripting that contains references to other types of XSS such as Stored XSS, reflected XSS and DOM based XSS all return 404 for the page https://owasp.org/www-community/DOM_Based_XSS, etc

The correct page seems to be at https://owasp.org/www-community/attacks/DOM_Based_XSS
Similarly for other types.

**Comment by GaloisGirl** [comment]
Same issue on https://owasp.org/www-community/attacks/xss/ .

All links in the "Related Security Activities" section and most internal links return 404.

**Comment by kingthorin** [comment]
Fixed in https://github.com/OWASP/www-community/pull/115
