### ISSUE TITLE
Broken links on XSS page

### ISSUE THREAD

**Issue by ndecizion** [OWASP/www-community#276]
Broken links can be found on https://owasp.org/www-community/attacks/xss/

Under the Related Security Activities heading, several links are broken
- Both links for OWASP Development Guide
- Phishing - should be https://wiki.owasp.org/index.php/Phishing ?
- Data Validation - should be https://wiki.owasp.org/index.php/Data_Validation ?
- OWASP Code Review Guide & Reviewing Code for Cross-site scripting - Goes to a migration landing page

Similarly under the References section, the following links are broken:
- Data Validation
- Testing_for_Reflected_Cross_site_scripting_(OWASP-DV-001) - should be https://wiki.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OTG-INPVAL-001) ?
- Testing_for_Stored_Cross_site_scripting_(OWASP-DV-002) - should be https://wiki.owasp.org/index.php/Testing_for_Stored_Cross_site_scripting_(OTG-INPVAL-002) ?
- Testing_for_DOM-based_Cross_site_scripting_(OWASP-DV-003) - should be https://wiki.owasp.org/index.php/Testing_for_DOM-based_Cross_site_scripting_(OTG-CLIENT-001) ?
- How to Build an HTTP Request Validation Engine (J2EE validation using OWASP’s Stinger)
- http://code.google.com/p/doctype/wiki/ArticlesXSS
- https://owasp.org/www-community/attacks/xss/XSS_Filter_Evasion_Cheat_Sheet

Also under References, this link should be updated
- http://www.cgisecurity.com/articles/xss-faq.shtml -> https://www.cgisecurity.com/xss-faq.html

**Comment by kingthorin** [comment]
The testing links should be updated per: https://owasp.org/www-project-web-security-testing-guide/#how-to-reference-wstg-scenarios (Not use wiki.owasp.org).

@ndecizion please feel free to open a PR with fixes. For the Dev Guide and Code Review Guide feel free to just remove the references, those projects seem to have died.
