### ISSUE TITLE
Posible fake website that accepts payments

### ISSUE THREAD

**Issue by b0ngz** [OWASP/www-community#311]
www-community/_data/tools.json cites "misterscanner.com" at the top most position of the table.
https://owasp.org/www-community/Vulnerability_Scanning_Tools

This website does not offer free scanning services.
The site redirects to Paypal's sandbox.paypal.com URL when you select the 6USD yearly plan. ( this website is used for development purposes)
All other pricier plans complete the payment process and charge.
After paying for a plan, the website immediately starts a "scan" on the selected domain without any DNS ownership validations. The results of this scan can't be found anywhere on the website and we never receive an email with the attached PDF of the results.
The chat function with "Alex" and email option never respond to our requests for help.
The website and email service are hosted on GoDaddy.

Please review this information and take appropriate action.

**Comment by kingthorin** [comment]
Thank you for this report, will investigate and action.

**Comment by ishaan654321** [comment]
I have already corrected the free trial version error and the tool faced some issues due to three COVID-related deaths in the past months. We were down for a couple of months with main developers in the isolation. We are even in the touch with the OWASP team to take the corporate sponsorship.

**Comment by kingthorin** [comment]
This content is maintained by volunteers who do not have the cycles to continually vet or revisit entries. If further problem reports arise from the inclusion of Abbey Scan/misterscanner we'll have no choice but to remove it permanently.
