### ISSUE TITLE
CRV2_AppThreatModeling needs updates

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-community#317]
https://github.com/OWASP/www-community/blob/master/pages/CRV2_AppThreatModeling.md

Contains a bunch of HTML based tables that need attention. They did not auto-migrate well and at a certain point break the rendering of the majority of the page.

**Comment by ADubhlaoich** [comment]
I can take a shot at this; is retaining the original "look" of the tables important?

Converting to pure markdown should be easy enough, and I'll also do a once-over on the page itself to see what could be improved.

**Comment by kingthorin** [comment]
To be honest I haven't dug into the content much. I doubt the "look" of the table mattered much.

The original is here: https://wiki.owasp.org/index.php/CRV2_AppThreatModeling If that helps.

**Comment by ADubhlaoich** [comment]
As an update to this, there is no clean way to convert straight HTML to Markdown as markdown tables do not have any "column span" (colspan) arguments for making clear headers  in its syntax, and the format for mediawiki is also messy - hence why the original author likely embedded HTML onto the page.

I am likely going to have to rewrite this entire page to make it readable, as the new website also has different display properties to the original wiki, such as its body width and font size. I'll get the images linked/working properly then start revising the page from the top down.

**Comment by ADubhlaoich** [comment]
I'm cleaning my hands of this; I've decided that redoing the entire page is far too much of my time, though someone can pick up [where I left off](https://docs.google.com/document/d/1KTpvJPkHIG3-LxayEOLSAK2cVxJoTZM243iiBejaHmo/edit?usp=sharing) if they want to approach it similarly.

I never quite figured out exactly what chunk of raw HTML breaks the page, but converting the tables to Markdown is the quick (Albeit messy) fix for this issue; do note as mentioned above, there is no convention for a multiple-column spanning table heading in Markdown. Even so, rewrites are still necessary - Markdown does not play well with the text in some of the tables, and even my best efforts to reduce text on tables were still distorted once rendered.

My apologies.

**Comment by kingthorin** [comment]
@ADubhlaoich totally understand, thanks for taking a crack at it.

**Comment by victoriadrake** [comment]
I'll take this.

**Comment by victoriadrake** [comment]
What's the CRV2 bit about?
