### ISSUE TITLE
in page source code analysis tools, graudit is mentioned to work on any OS but it does not

### ISSUE THREAD

**Issue by gogo2464** [OWASP/www-community#318]
In the page https://owasp.org/www-community/Source_Code_Analysis_Tools There is no comment about the architecture of graudit.

It let think that graudit works on any platform. Actually it is more destined to linux users. It does not compile on windows with no cygwin and 80% of the code is bash script. 

So I suggest to add "linux" in the tab architecture of the array of the line graudit.

**Comment by kingthorin** [comment]
Thanks for letting us know, if you feel up for contributing further you can open a Pull Request for us with the modification. Just need to tweak the entry in this file: https://github.com/OWASP/www-community/blob/master/_data/tools.json
