### ISSUE TITLE
Control_flow_graph not found (broken)

### ISSUE THREAD

**Issue by isfahany** [OWASP/www-community#322]
I am reading this [this](https://github.com/OWASP/www-community/blob/master/pages/controls/Static_Code_Analysis.md) page and I cannot see the [control flow graph image.](
https://github.com/OWASP/www-community/blob/master/pages/controls/Control_flow_graph.png) I realize that the image is not exist. I dont know how the image look like so I can't modify it and make a PR, so I make this issue and hope someone can fix it out.

**Comment by kingthorin** [comment]
It could be grabbed from: https://wiki.owasp.org/index.php/Static_Code_Analysis and put into `assets/images/` and referenced relatively (there are other examples if you search the repo content).

**Comment by isfahany** [comment]
I've made a PR. but, I found another broken image link when I  was looking for examples in repo. It affect the OWASP www-community page such as [Certificate and Public Key Pinning Page](https://owasp.org/www-community/controls/Certificate_and_Public_Key_Pinning). I do believe there are a lot more broken image link.
