### ISSUE TITLE
Ambiguous DOM-based XSS definition

### ISSUE THREAD

**Issue by FINDarkside** [OWASP/www-community#391]
There seems to be 2 different definitions for DOM-based XSS
* https://owasp.org/www-community/attacks/DOM_Based_XSS
* https://owasp.org/www-community/Types_of_Cross-Site_Scripting
First one reads
> DOM Based XSS (or as it is called in some texts, “type-0 XSS”) is an XSS attack wherein the attack payload is executed as a result of modifying the DOM “environment” in the victim’s browser used by the original client side script, so that the client side code runs in an “unexpected” manner. That is, the page itself (the HTTP response that is) does not change, but the client side code contained in the page executes differently due to the malicious modifications that have occurred in the DOM environment.

And the second one
> DOM Based XSS is a form of XSS where the entire tainted data flow from source to sink takes place in the browser, i.e., the source of the data is in the DOM, the sink is also in the DOM, and the data flow never leaves the browser.

Consider a case where SPA retrieves data from json api, and insecurely inserts the data on the page using `innerHTML`. It looks like it would fit the first definition of DOM-based XSS, but not the second. 

Many sources seem to define DOM-based xss in a way that my example would fall under it. Examples:
* https://dl.acm.org/doi/abs/10.1145/2508859.2516703
>  DOM-based XSS [16], a vulnerability class subsuming all Cross-site Scripting problems that are caused by insecure handling of untrusted data through JavaScript.
* https://dl.acm.org/doi/10.5555/2671225.2671267
> In contrast to the server-side variants of XSS, namely reflected and persistent, the term DOM-based Cross-Site Scripting (or DOM-based XSS) subsumes all classes of vulnerabilities which are caused by insecure client-side code
* https://research.google/pubs/pub49950/
Context being DOM-based XSS attacks:
> For readability, the example in Fig. 1 is artificially simple, which may convey a false impression that XSS vulnerabilities are not difficult to detect or mitigate. In reality, the information flow from XSS sources to sinks can be extremely complex and often goes through servers and databases
>  It is a typical client-side XSS vulnerability, aka. DOM-based XSS.
* https://dl.acm.org/doi/10.1016/j.cose.2011.12.004
> We do not address DOM-based (Type III) XSS attacks, where trusted client-side JavaScript permits the injection of untrusted content in violation the web application’s security policy

**Comment by jmanico** [comment]
I do not believe DOM XSS is a proper attack category. There are only two ways to introduce XSS into a web application and that is either stored or reflected. The other scenarios are more contrived.

“DOM XSS” is really only a defensive category.

--
Jim Manico
@Manicode

**Comment by Prakhar-Shankar** [comment]
@kingthorin 
Hey are we still working on this issue? If yes, kindly suggest me the changes.
Thanks.
