### ISSUE TITLE
CSV Injection Remediation

### ISSUE THREAD

**Issue by lauritzh** [OWASP/www-community#443]
Hi all,

I recently stumbled over the following behavior:

Consider an implementation that follows [this](https://owasp.org/www-community/attacks/CSV_Injection) recommendation:
> Alternatively, prepend each cell field with a single quote, so that their content will be read as text by the spreadsheet editor.

The following CSV file could be exported by that implementation:
```csv
a,b,c
d,e,'=1+1;=1+2
```

Opening the above example results in evaluation of the latter formula in Excel:
![image](https://user-images.githubusercontent.com/19983249/123099909-ea57ad80-d432-11eb-994a-a504c2540561.png)

As well as in LibreOffice:
![image](https://user-images.githubusercontent.com/19983249/123100315-4c181780-d433-11eb-83d0-36677b27dcf7.png)

Even closing the string using a second single quote (`'`) does not mitigate this for all user agents, as some UAs still prefer the semicolon over the comma (e.g. LibreOffice). 

What would be the best recommendation to escape semicolons in CSV files that use  commas as delimiters throughout the document?

**Comment by chrrel** [comment]
I agree with @lauritzh that the current recommendation does not pose a sufficient solution in all situations. After some experiments I came to the following conclusion:

A technique working for MS Excel and LibreOffice would be to perform the following steps for all cells containing untrusted data:

* Wrap each cell field in double quotes
* Prepend each cell field with a single quote
* Escape every double quote using an additional double quote

Two examples:

| Input         | Escaped Output    | 
| ------------- |:----------------: |
| `=1+2";=1+2`  | `"'=1+2"";,=1+2"` | 
| `=1+2'" 	;,=1+2` | `"'=1+2'"" 	;,=1+2"` |

So far, I did not find a way to circumvent these measures.

**Comment by lauritzh** [comment]
Hi @chrrel!

Thank you very much for adding your thoughts.
I can confirm that your proposed recommendation also works for *Apple Numbers*:
```csv
a,b
"'=1+2"";,=1+2","'=1+2'"" ;,=1+2"
```
![image](https://user-images.githubusercontent.com/19983249/123316021-a5b03d00-d52c-11eb-97e5-93f55756363b.png)

**Comment by kingthorin** [comment]
Do one of you intend to submit a fix for this?
