### ISSUE TITLE
OWASP Filter's Project - Status?

### ISSUE THREAD

**Issue by decidedlygray** [OWASP/www-community#483]
Hello,

I am working through proof-reading the OWASP community pages for quality and accuracy. I see several pages that reference the OWASP Filters Project, but have no associated link to the project's home page. In a non-OWASP web page I found that the OWASP Common Library (OCL) project may have absorbed the OWASP Filters Project, but I am also unable to find that project's home page. Neither of those projects appear in the [list of OWASP Projects](https://owasp.org/projects/).

I was wondering:
Does the OWASP Filters Project still exist?
Does the OWASP Common Library Project still exist?
Depending on those answers, should I submit PRs to remove references to them in the existing community pages?

Examples of pages with references:
- https://owasp.org/www-community/Injection_Flaws
- https://owasp.org/www-community/Improper_Error_Handling

**Comment by kingthorin** [comment]
I’m not aware of either having any true presence/deliverable. I’m fine with references being dropped.

@hblankenship are you aware of anything I might be missing or overlooking?

**Comment by hblankenship** [comment]
Nope. Those projects were archived before I came aboard, I believe.
