### ISSUE TITLE
404 - Not Found for Threat Modeling Outputs topic

### ISSUE THREAD

**Issue by ankitce** [OWASP/www-community#49]
The post with title '[Application Threat Modeling](https://owasp.org/www-community/Application_Threat_Modeling)' contains a broken reference link.
The URL of the reference is https://owasp.org/www-community/Threat_Modeling_Outputs whose corresponding page does not exist.

**Comment by breencp** [comment]
I am looking for a solution as well.

**Comment by kingthorin** [comment]
Fixed in https://github.com/OWASP/www-community/pull/73
