### ISSUE TITLE
How to solve the problem of double encoding

### ISSUE THREAD

**Issue by 2MoonStop** [OWASP/www-community#530]
When I pass in the value of "%27%Balert%28361%29%2B%27", it cannot handle this value.
look forward to your reply

**Comment by 2MoonStop** [comment]
what should i do?  first of all decode this value?

**Comment by kingthorin** [comment]
That's probably covered in: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html

If you want to discuss further I'd suggest posting to #appsec on the [OWASP slack](https://owasp.org/slack). ([Self invite here](https://owasp.org/slack/invite))
