### ISSUE TITLE
404 - "How to Protect Yourself" (Line 160)

### ISSUE THREAD

**Issue by shed-00** [OWASP/www-community#54]
The link 
[OWASP XSS Prevention Cheat Sheet]
(XSS_\(Cross_Site_Scripting\)_Prevention_Cheat_Sheet "wikilink")
is redirecting to this page,
https://owasp.org/www-community/attacks/xss/XSS_/(Cross_Site_Scripting/)_Prevention_Cheat_Sheet
but should be going to this page:
https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet

**Comment by kingthorin** [comment]
Fixed in https://github.com/OWASP/www-community/pull/115
