### ISSUE TITLE
Skill level scale in OWASP_Risk_Rating_Methodology.md is wrong

### ISSUE THREAD

**Issue by tonigonzalez** [OWASP/www-community#564]
The scale should be reversed. The less skill required to successfully execute an attack, the higher the likelihood of it happening.

`No technical skills (1), some technical skills (3), advanced computer user (5), network and programming skills (6), security penetration skills (9)`

**Comment by kingthorin** [comment]
Duplicate https://github.com/OWASP/www-community/issues/431

**Comment by kingthorin** [comment]
Also please read the “DISCLAIMER” at the top of the page.
