### ISSUE TITLE
Is it supposed to be `the string-concatenation of _name_ and *" accessor storage"*`?

### ISSUE THREAD

**Issue by dpuga1** [OWASP/www-community#578]
Is it supposed to be `the string-concatenation of _name_ and *" accessor storage"*`?

__Originally posted by @jmdyck in https://github.com/tc39/ecma262/pull/2417#discussion_r824158716__

**Comment by kingthorin** [comment]
Could you be more specific?

**Comment by ljharb** [comment]
@kingthorin this is either an accidental issue creation or spam; i suspect you can summarily close/delete it.

**Comment by kingthorin** [comment]
Thanks

**Comment by heaartlless5958** [comment]
Recently I got to know few things about my device and Gmail I'd so I wanted
to know about that can I get any contact to discuss about.
