### ISSUE TITLE
On the right, with the bar containing all the brushes and tools and stuff, hovering your cursor shows other options (hovering over the mask box shows other mask options, for example). Sliding your cursor whilst clicking allows you to select between them. However for me at least it's annoying, and I would like a way to turn this off.

### ISSUE THREAD

**Issue by dpuga1** [OWASP/www-community#589]
On the right, with the bar containing all the brushes and tools and stuff, hovering your cursor shows other options (hovering over the mask box shows other mask options, for example). Sliding your cursor whilst clicking allows you to select between them. However for me at least it's annoying, and I would like a way to turn this off.

__Originally posted by @Pythagoras-314 in https://github.com/aseprite/aseprite/issues/3215__

**Comment by kingthorin** [comment]
@dpuga1 why do you keep posting these useless items to our repo?

**Comment by Pythagoras-314** [comment]
my man literally just copied my suggestion.
Cringe
