### ISSUE TITLE
CSRF page: broken link to CSRF Prevention Cheat Sheet

### ISSUE THREAD

**Issue by JeffreyCA** [OWASP/www-community#61]
On the CSRF page (https://owasp.org/www-community/attacks/csrf), the link to the CSRF Prevention Cheat Sheet under the **How to Prevent CSRF Vulnerabilities** heading is broken. It should point to https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.

**Comment by rbsec** [comment]
@JeffreyCA @kingthorin this can be closed, was fixed in #68

**Comment by kingthorin** [comment]
Thanks

For future reference you can use keywords to close issues when PRs are merged:
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
