### ISSUE TITLE
Why not use CWE in vulnerability list?

### ISSUE THREAD

**Issue by yhojann-cl** [OWASP/www-community#610]
In vulnerability list https://owasp.org/www-community/vulnerabilities/ why not use CWE categorization?

**Comment by kingthorin** [comment]
Feel free to add CWE mappings.
We look forward to your PR(s).

**Comment by yhojann-cl** [comment]
Done! https://github.com/OWASP/www-community/pull/611 but there are still several pages left.

**Comment by kingthorin** [comment]
Per above, some of this is done, community members can feel free to tackle further as wanted.
