### ISSUE TITLE
Polyspace tool information incorrect 

### ISSUE THREAD

**Issue by plal22** [OWASP/www-community#614]
Hi 

I am a Product Manager for Polyspace. I would like to request 2 corrections:

1. Change the name from "Polyspace Static Analysis" to "Polyspace Static Analysis Tools" since there are more than one tool. 
2.  These tools are not open source or free and should be shown as commercial

Thanks,

**Comment by kingthorin** [comment]
The information is open and editable.

I can probably look at tackling this in the next few days I guess.

**Comment by kingthorin** [comment]
https://github.com/OWASP/www-community/blob/master/_data/tools.json
