### ISSUE TITLE
email validation regex

### ISSUE THREAD

**Issue by butterywombat** [OWASP/www-community#640]
Hi all,
I am wondering if https://github.com/OWASP/www-community/blob/master/pages/OWASP_Validation_Regex_Repository.md needs to be updated for top level domains (https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains https://www.iana.org/domains/root/db). There seems to be many that are longer than 7 characters. 

Asking as we are using the OWASP recommended regex for our validations which would cause some valid existing emails in our db to be blocked now.

Thank you

**Comment by kingthorin** [comment]
Feel free to submit a PR modifying the content. It's meant to be community generated/maintained.

I've just done some formatting tweaks in: https://github.com/OWASP/www-community/pull/641

**Comment by butterywombat** [comment]
pr here: https://github.com/OWASP/www-community/pull/642
