### ISSUE TITLE
SSRF page has heading for security controls but does not list them

### ISSUE THREAD

**Issue by allensutton-lumen** [OWASP/www-community#646]
The page at this URL: https://github.com/OWASP/www-community/blob/master/pages/attacks/Server_Side_Request_Forgery.md
...has a section for security controls to stop SSRF attacks, but does not actually list them.

**Comment by kingthorin** [comment]
Yup that content was auto-migrated and looking at the original (https://wiki.owasp.org/index.php/Server_Side_Request_Forgery), there never was any.

I'll remove the heading.

**Comment by kingthorin** [comment]
Actually I'll link to the SSRF Prevention Cheat Sheet.
