### ISSUE TITLE
Bad link on the OWASP Risk Rating Methodology Page

### ISSUE THREAD

**Issue by DanielOjalvo** [OWASP/www-community#665]
The "Practical Threat Analysis" link in the references on https://owasp.org/www-community/OWASP_Risk_Rating_Methodology currently points to a website selling steroids which I don't believe was the intention of the author, unless a very unorthodox risk-rating system is being suggested.

[Practical Threat Analysis](http://www.ptatechnologies.com/)
http://www.ptatechnologies.com/

Cheers

**Comment by kingthorin** [comment]
Thanks
