### ISSUE TITLE
"<" symbol with text inputs getting cleared, after applied the sanitizer.

### ISSUE THREAD

**Issue by SasiprabuK** [OWASP/www-community#667]
Given inputs cleared, after apply sanitize for "<" with text inputs

Dependency - owasp-java-html-sanitizer
version - 20200713.1

Eg:
**Sanitize <Data Check** ==> (After sanitize) ==> **Sanitize**
<Data Check - after the < symbol with further text inputs cleared completely.
I have checked with latest version too. but, still same issue occurred.
Please guide me, to solve this scenario.

**Comment by kingthorin** [comment]
Please report this issue via the appropriate repo/ticketing system. OWASP is huge with many projects. This is not a www-community issue.

**Comment by SasiprabuK** [comment]
sure @kingthorin
