### ISSUE TITLE
B00 comments in sample code

### ISSUE THREAD

**Issue by mkuligPSI** [OWASP/www-community#681]
I have read https://github.com/OWASP/www-community/blob/master/pages/Hibernate.md. It contains sample code and I noticed 
`/*B00*/`
comment in 3 places. What does it mean? I guess that it means disapproval or disagreement  but I have no idea why two zeroes are used instead of two letters **o**.

**Comment by kingthorin** [comment]
I have no idea. You could look at the original: https://wiki.owasp.org/index.php/Hibernate perhaps you can hit up the author and ask.

I looked quickly, it seems to be associated with SQL use, so perhaps places that are subject to SQLi?

**Comment by kingthorin** [comment]
I think it’s meant to represent the word “boo” and indicate pleases SQLi might be an issue.

**Comment by PavanButke** [comment]
hi @kingthorin  can I work on this. Could you please assign it to me.

**Comment by kingthorin** [comment]
@PavanButke ?

**Comment by Prakhar-Shankar** [comment]
/ assign
