### ISSUE TITLE
Migrate Favicon DB Content

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-community#684]
https://wiki.owasp.org/index.php/OWASP_favicon_database is referenced by https://tryhackme.com/room/contentdiscovery

we should migrate it to the new site.

**Comment by HimanshHK** [comment]
Hello Sir, I am Himanshu. I am interested to work on this. Can you please assign me this.

**Comment by kingthorin** [comment]
It would probably been a good move to implement this as a data file with a template/include. That way maintenance will be easier.

For an example check the api-tools yaml and html in the repo.

**Comment by HimanshHK** [comment]
Sure Sir, I will do it as fast as possible.

**Comment by HimanshHK** [comment]
Sir, I am not getting what's actually the issue here. Can you please explain that and will you please tell me how to run the project?

**Comment by kingthorin** [comment]
That was covered in earlier comments.

Info on local testing can be found here: https://owasp.org/migration/ (toward the bottom of the page).

**Comment by kingthorin** [comment]
@HimanshHK do you still intend to tackle this?

**Comment by nikhil25803** [comment]
Hey @kingthorin | Can you assign me this?
Would love to work on this

**Comment by nikhil25803** [comment]
As read earlier in the comments, referencing from `api-tools.yml`. On the [webpage]() we have a favicons database such as `6399cc480d494bf1fcd7d16c42b1c11b:penguin`. 
So what should I name this the respective .yml file I'll create
Eg.
```yml
- name: "penguin"
  id: "6399cc480d494bf1fcd7d16c42b1c11b"
```

**Comment by kingthorin** [comment]
There are some more entries and sources here that you could add as well: https://vulners.com/openvas/OPENVAS:136141256231020108

**Comment by nikhil25803** [comment]
Understood, will update you soon with the PR :)
