### ISSUE TITLE
Threat_Modeling_Process missing reference

### ISSUE THREAD

**Issue by rfromh** [OWASP/www-community#694]
Threat_Modeling_Process.md is missing some reference with explanation about Application Security Frame (ASF).

I could not find significant search results on google about ASF. There is no reference in the document. Would it make sense to include a reference to a resource with more details?

**Comment by kingthorin** [comment]
Well if you didn’t find something to link then I guess not?

**Comment by kingthorin** [comment]
The text should just be edited removing the or clause in that sentence.

**Comment by rfromh** [comment]
The text references this ASF a few times, not only in that one sentence. It seems to be well defined further down but it says ASF has categories "such as", "e.g.". It is not compleley defined in the document. 
I see thre options: 
- Find a valid reference to ASF so that the definition is clear.
- Enhance the definition ASF so that it is complete.
- Remove this ASF reference completely.

**Comment by kingthorin** [comment]
@victoriadrake you're the original creator of this content, thoughts/input?

**Comment by kingthorin** [comment]
>  It seems to be well defined further down but it says ASF has categories "such as", "e.g.". 

Mathis document isn’t meant to repeat everything from another source.

My advice is: Either link it if you know the source or drop the references if you don’t.

**Comment by Prakhar-Shankar** [comment]
/ assign

**Comment by Prakhar-Shankar** [comment]
@kingthorin I have already created a PR kindly review it.
