### ISSUE TITLE
Redirection or indication of the OWASP Secure Headers Project existence

### ISSUE THREAD

**Issue by righettod** [OWASP/www-community#757]
Hi,

I think that it can be interesting to update the following page:

https://github.com/OWASP/www-community/blob/master/pages/Security_Headers.md

To refer to or indicate a reference to the [OWASP Secure Headers Project](https://owasp.org/www-project-secure-headers/).

What do you think?

Thanks a lot in advance 😃

**Comment by kingthorin** [comment]
Sure feel free to add a link. It’s community content, you don’t need to ask, just go ahead and PR changes or additions.

**Comment by righettod** [comment]
Done 😃
