### ISSUE TITLE
New DAST tool (Codename SCNR)

### ISSUE THREAD

**Issue by Zapotek** [OWASP/www-community#949]
Hello,

I would like this new DAST tool to be included in the relevant list.

Name: Codename SCNR
License: Commercial (Free community version exists)
Company: Ecsypno

https://ecsypno.com/pages/codename-scnr

Cheers!

**Comment by kingthorin** [comment]
Go for it

**Comment by Zapotek** [comment]
PR: https://github.com/OWASP/www-community/pull/950
