### ISSUE TITLE
SAST Tools contains several of outdated / unmaintained tools

### ISSUE THREAD

**Issue by dnperfors** [OWASP/www-community#971]
While looking through the tools list for SAST tools, I noticed that several tools are no longer available (OWASP Code Crawler) or hopelessly outdated (FxCop) or unmaintained (.NET Security Guard)
(As you may notice, these are all .NET focused SAST tools, didn't look at others)

What would be the best way to indicate this? Remove them, add extra note, or add an extra column with alternative or status?

**Comment by kingthorin** [comment]
I'd suggest simply removing them.
