### ISSUE TITLE
Hyperlink Redirect User to Malicious Gambling Site

### ISSUE THREAD

**Issue by termireum** [OWASP/www-community#972]
Hi OWASP Team,

I would like to report this link "[Busting Frame Busting: A study of clickjacking vulnerabilities on top sites](http://w2spconf.com/2010/papers/p27.pdf)" redirect user to gambling site.

Source: https://owasp.org/www-community/attacks/Clickjacking

![Screenshot from 2024-06-18 16-41-43](https://github.com/OWASP/www-community/assets/72587681/d85029ae-9034-49a1-96ae-763a19d13709)

**Comment by psiinon** [comment]
There is a "Edit on GitHub" link on that page, thats what i followed 😁
