### ISSUE TITLE
Kayran Tool Change name to "Cytrix"

### ISSUE THREAD

**Issue by KayranManage** [OWASP/www-community#998]
Change to: 

{
      "title": "Cytrix",
      "url": "https://cytrix.io/",
      "owner": "Cytrix",
      "license": "Commercial",
      "platforms": "All Web Applications Supported",
      "note": "Automatic Penetration Testing for Web Applications & API Schema Penetration Testing",
      "type": "DAST"
   }

**Comment by kingthorin** [comment]
So submit a PR adjusting it??

**Comment by ayyushx** [comment]
@KayranManage Made the required changes
