### ISSUE TITLE
Cytrix API Tools

### ISSUE THREAD

**Issue by KayranManage** [OWASP/www-community#999]
- name: "Cytrix"
  link: "https://cytrix.io/"
  from: "Cytrix"
  license: "https://img.shields.io/badge/License-Commercial-9cf.svg"
  platforms: "https://img.shields.io/badge/Platform-SaaS-inactive.svg"
  posture: "https://img.shields.io/badge/API_Posture-No-red.svg"
  runtime: "https://img.shields.io/badge/API_Runtime-No-red.svg"
  testing: "https://img.shields.io/badge/API_Testing-Yes-brightgreen.svg"
  notes: "API Penetration Testing tools (Postman, Swagger, GraphQL, HAR file and more !"

**Comment by kingthorin** [comment]
So submit a PR adjusting it??
